twilio:
  account-sid: ACdf2676753d81814c50b7115c5617a9a4
  auth-token: b94932d45ef4af3f720d5096a94f9f19
  from-number: "+19136751850"

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: playzzzaid@gmail.com
    password: edse cxrp xysc nfhz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'



  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 980304959413-ltjpmn920d55loc7ddc831s56bdr5pa4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            #redirect-uri: "https://3e4367127e0f.ngrok-free.app/api/sunduk-service/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  data:
    mongodb:
      host: localhost
      port: 27017
      database: MyDB

server:
  port: 8080
  servlet:
    context-path: /api/sunduk-service
    session:
      timeout: 60m
      cookie:
        same-site: none
        secure: true
  tomcat:
    background-processor-delay: 60

sunduk:
  security:
    exclude-paths:
      - /api/sunduk-service/oauth2/authorization
      - /api/sunduk-service/login/oauth2/code
      - /api/sunduk-service/custom-logout
      - /api/sunduk-service/custom-login
      - /api/sunduk-service/upload-contact
      - /api/sunduk-service/webhook



exchange:
  api:
    url: https://v6.exchangerate-api.com/v6/b4373c5a26b8292e2e1cbd8b

stripe:
  key:
    secret: sk_test_51RohZUFjIPvwIVrLyRAcI7OWRbYVmEZ976vhMmJDyYyXeCDkpxE0ZPA5XUr7xxqw168zJTtU9S8S5YFFNHoKyYPR00MaFmFn8l
  webhook:
    secret: whsec_ada8e07c83edd36fb4e5110e64dd53607228345dd6520476ab01dd208701e6b5

logging:
  level:
    com.bxb.sunduk_pay: DEBUG