spring:
  config:
    import: classpath:queries.yml

  mail:
    host: smtp.gmail.com
    port: 587
    username: playzzzaid@gmail.com
    password: edse cxrp xysc nfhz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/SundukPay
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

  jackson:
    time-zone: Asia/Kolkata

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 19887003498-6uum0ho83vf44vkm7m68tqts5judp0n4.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  data:
    mongodb:
      host: localhost
      port: 27017
      database: MyDB

server:
  port: 8080
  servlet:
    context-path: /api/sunduk-service
    session:
      timeout: 60m
      cookie:
        same-site: none
        secure: true
  tomcat:
    background-processor-delay: 60

twilio:
  account-sid: ACdf2676753d81814c50b7115c5617a9a4
  auth-token: b94932d45ef4af3f720d5096a94f9f19
  from-number: "+19136751850"

sunduk:
  security:
    exclude-paths:
      - /api/sunduk-service/oauth2/authorization
      - /api/sunduk-service/login/oauth2/code
      - /api/sunduk-service/custom-logout
      - /api/sunduk-service/custom-login
      - /api/sunduk-service/upload-contact
      - /api/sunduk-service/webhook

exchange:
  api:
    url: https://v6.exchangerate-api.com/v6/136cca7e5f6ec25648bc5eca

stripe:
  key:
    secret: sk_test_51RpVpD95xk3wBgccWhhepgDwxZwDAt4QM8huVR4W0kYhivEUljSw2untlADI2TJsMVBatxVpcCPCoLQft89NkwoO00bGWRE8xR
  webhook:
    secret: whsec_3e927c453a257e87bdd1e7955b41653afb52feec4282321a0235ecb5c8dde6a6

resilience4j:
  circuitbreaker:
    instances:
      stripeGateway:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bxb.sunduk_pay: DEBUG
